#!/bin/bash
# ©, 2022, Casey Witt
# developed with zfs-0.8.3
# hosted at https://github.com/varasys/zfsync
# script linted with shellcheck (https://www.shellcheck.net/)
# initially meant to be posix sh compatable, but could not work out reliable enough error handling with posix sh

# note that ~/.ssh/authorized_keys file on the backup server must have an entry of the following form:
# restrict,command="zfsync server pool/path" ssh-ed25519 <key> [comment]

# [ ] TODO implement pre/post send/receive hooks (for cascade backups)
# [ ] TODO implement localhost mirroring (without ssh)
# [ ] TODO implement pruning (maybe; consider this may be best for seperate script; or may be best for this script to prune on remote also)
# [ ] TODO implement creating dummy datasets on backup server for broken chains (probably not; let the user do this manually??)
# [*] TODO update sync logic to check for new latest snapshot after each send
# [*] TODO config zfsync user (as sender and receiver)

set -euo pipefail # fast fail on errors, undefined variables, and pipeline errors

AUTOSNAPPROP="${AUTOSNAPPROP:-"com.sun:auto-snapshot"}" # dataset user property (set false to exclude dataset from snapshoting and backups)
AUTOMIRRORPROP="${AUTOMIRRORPROP:-"${AUTOSNAPPROP}"}"
SNAPPREFIX="${SNAPPREFIX:-"zfsync_"}" # prefix for snapshot name
DATECMD="${DATECMD:-"date -u +%F_%H-%M-%S_UTC"}" # command to generate snapshot name timestamp

ERR=0 # error counter (incremented when error function is called)
trap 'exit $ERR' EXIT # note that the connect function redefines this if it is called

log() {
  MSG="$1"; shift
  # shellcheck disable=2059 # allow variable in printf format string
  printf "\e[1m${MSG}\e[0m\n" "$@" >&2
}

debug() {
  if [ "${DEBUG:-}" = true ]; then # this will be set when first command line argument is "-d"
    MSG="$1"; shift
    # shellcheck disable=2059 # allow variable in printf format string
    printf "\e[1m\e[4;36m${MSG}\e[0m\n" "$@" >&2
  fi
}

warn() {
  MSG="$1"; shift
  # shellcheck disable=2059 # allow variable in printf format string
  printf "\e[1m\e[35m${MSG}\e[0m\n" "$@" >&2
}

error() {
  MSG="$1"; shift
  # shellcheck disable=2059 # allow variable in printf format string
  printf "\e[1m\e[31m${MSG}\e[0m\n" "$@" >&2
  ERR=$((ERR+1))
}

fatal() {
  MSG="$1"; shift
  # shellcheck disable=2059 # allow variable in printf format string
  printf "\e[1m\e[31m${MSG}\e[0m\n" "$@" >&2
  exit 1
}

snap() {
  SNAPSHOT="${SNAPPREFIX}$(${DATECMD})"
  SNAPSHOTS="$(zfs list -Ho "name,${AUTOSNAPPROP}" -s name "$@" \
    | awk -v suf="@${SNAPSHOT}" '{ if ($2 != "false") print $1 suf }')"
  if [ -n "${SNAPSHOTS}" ]; then
    #shellcheck disable=2086 # do not quote variable
    zfs snap ${SNAPSHOTS}
    for SNAP in ${SNAPSHOTS}; do
      zfs bookmark "${SNAP}" "${SNAP//\@/\#}"
    done
    #shellcheck disable=2086 # do not quote variable
    zfs list -t snapshot,bookmark ${SNAPSHOTS} ${SNAPSHOTS//\@/\#}
  fi
}

connect() {
  if [ -z "${RPC:-}" ]; then # don't reconnect if $RPC is already defined
    HOST="$1"
    SOCKET="${HOME}/.ssh/zfsync_${HOST}_$(date +%s%N)"
    log 'connecting to ssh host: %s ...' "${HOST}"
    ssh -fMN -S "${SOCKET}" "${HOST}"
    # shellcheck disable=2064 # expand HOST and SOCKET at definition time
    trap "
      log 'disconnecting from ssh host: %s ...' '${HOST}'
      ssh -S '${SOCKET}' -O exit '${HOST}'
      exit \$ERR
    " EXIT
    RPC=$(printf '%s -o ControlMaster=no -S %s %s' "$(command -v ssh)" "${SOCKET}" "${HOST}")
    export RPC # need to export so function subshells have access
  fi
}

create_remote() {
  SOURCE="$1"
  FIRST=$(zfs list -t snap -Ho name -s creation "${SOURCE}" | head -n 1)
  zfs send -DLcew "${FIRST}" | mbuffer -s 128k -m 1G | $RPC receive -s "${SOURCE}"
}

resume_remote() {
  SOURCE="$1"
  TOKEN="$2"
  zfs send -e -t "${TOKEN}" | mbuffer -s 128k -m 1G | $RPC receive -s "${SOURCE}"
}

update_remote() {
  SOURCE="$1"
  REMOTEGUID="$2"
  STARTSNAP="$(zfs list -Ho name,guid -t snapshot -s creation "${SOURCE}" \
    | awk "\$2 == ${REMOTEGUID} { print \$1 }")"
  # if STARTSNAP is not found then search bookmarks
  [ -n "${STARTSNAP}" ] || STARTSNAP="$(zfs list -Ho name,guid -t bookmark -s creation "${SOURCE}" \
    | awk "\$2 == ${REMOTEGUID} { print \$1 }")"
  [ -n "${STARTSNAP}" ] || { error "can't find snapshot/bookmark for guid=%s" "${REMOTEGUID}"; exit 1; }
  FINISHSNAP="$(zfs list -t snap -Ho name -S creation "${SOURCE}" | head -n 1)"
  zfs send -DLcew -I "${STARTSNAP}" "${FINISHSNAP}" | mbuffer -s 128k -m 1G | $RPC receive -s "${SOURCE}"
}

mirror() {
  DATASETS="$(zfs list -Ho "name,${AUTOMIRRORPROP}" -s name "$@" \
    | awk '{ if ($2 != "false") print $1 }')"
  for DATASET in ${DATASETS}; do
    ( # operate in a subshell so fatel error won't exit script
      log '\nmirroring %s ...' "${DATASET}"
      STATUS="$($RPC status "${DATASET}")"
      until
        debug 'remote STATUS: %s' "$STATUS"
        GUID="$(zfs list -t snap -Ho guid -S creation "${DATASET}" | head -n 1)" || fatal 'error querying guid for %s' "${DATASET}"
        debug 'local GUID: %s' "$GUID"
        [ -z "${GUID}" ] && error "error mirroring %s - no existing snapshots" "${DATASET}" && continue
        [ "${GUID}" = "${STATUS#guid=}" ] && debug 'complete: %s synced to GUID=%s' "${DATASET}" "${GUID}"
      do
        case "${STATUS}" in
          receive_resume_token=*)
            log 'resuming: %s ...' "${DATASET}"
            STATUS="$(resume_remote "${DATASET}" "${STATUS#receive_resume_token=}")" || fatal 'error resuming %s' "${DATASET}"
            ;;
          guid=*)
            log 'updating %s (%s => %s) ...' "${DATASET}" "${STATUS}" "${GUID}"
            STATUS="$(update_remote "${DATASET}" "${STATUS#guid=}")" || fatal 'error updating %s' "${DATASET}"
            ;;
          *)
            log 'creating: %s ...' "${DATASET}"
            STATUS="$(create_remote "${DATASET}")" || fatal 'error creating remote %s' "${DATASET}"
            ;;
        esac
      done
    )
  done
}

server() { # run from authorized_keys file on the backup server (ie. command="zfsync receive zpool/backups")
  TARGET="$1" # the dataset path prefix including pool name (ie. zpool/backups)
  # shellcheck disable=2086 # use word splitting below
  set -- $SSH_ORIGINAL_COMMAND
  SUBCMD="$1"; shift
  case "${SUBCMD}" in
    status)
      SOURCE="$1"
      TOKEN="$(zfs list -Ho receive_resume_token "${TARGET}/${SOURCE}" 2>/dev/null)"
      if [ "${TOKEN}" = "-" ]; then # dataset exists so check for guid
        GUID="$(zfs list -t snapshot -Ho guid -S creation "${TARGET}/${SOURCE}" | head -n 1)"
        if [ -n "${GUID}" ]; then
          TOKEN="guid=${GUID}" # respond with the guid
        else
          TOKEN="detached" # the dataset exists, but has no snapshots
        fi
      elif [ -n "${TOKEN}" ]; then # there is a resume token (which is not '-') so use it
        TOKEN="receive_resume_token=${TOKEN}"
      else
        TOKEN='missing'
      fi
      printf '%s' "${TOKEN}"
      ;;
    recv|receive)
      ARGS="$*"
      OPTIONS="${ARGS% *}"
      DATASET="${ARGS##* }"
      [ "${OPTIONS}" != "${DATASET}" ] || OPTIONS=""
      # [ -n "${PRERECEIVEHOOK}" ] && { ${PRERECEIVEHOOK} "${TARGET}" || true; } # run pre-receive hook if defined
      # shellcheck disable=2086 # don't quote OPTIONS
      mbuffer -s 128k -m 1G | zfs receive ${OPTIONS} "${TARGET}/${DATASET}"
      # [ -n "${POSTRECEIVEHOOK}" ] && { ${POSTRECEIVEHOOK} "${TARGET}" || true; } # run post-receive hook if defined
      TOKEN="$(SSH_ORIGINAL_COMMAND="status ${DATASET}" server "${TARGET}")"
      debug 'post receive token: %s' "${TOKEN}"
      printf '%s' "${TOKEN}"
      ;;
    send|list|destroy)
      ARGS="$*"
      OPTIONS="${ARGS% *}"
      DATASET="${ARGS##* }"
      [ "${OPTIONS}" != "${DATASET}" ] || OPTIONS=""
      # shellcheck disable=2086 # don't quote OPTIONS
      zfs "${SUBCMD}" ${OPTIONS} "${TARGET}/${DATASET}"
      ;;
    *)
      #shellcheck disable=2016 # don't expand %s below
      error 'fatal error: unknown command `%s`\n' "$SSH_ORIGINAL_COMMAND"
      exit 1
      ;;
  esac
}

configuser() {
  USER="${1:-"zfsync"}"
  HOMEDIR="${2:-"${HOMEDIR:-"/etc/zfsync"}"}"
  if id "${USER}" >/dev/null 2>&1; then
    warn 'user %s already exists' "${USER}"
  else
    useradd --home-dir "${HOMEDIR}" --no-create-home \
      --shell "$(command -v bash || command -v sh)" --system "${USER}"
    log 'user %s created' "${USER}"
  fi
  if [ -d "${HOMEDIR}" ]; then
    warn 'home directory %s already exists' "${HOMEDIR}"
  else
    mkdir -p "${HOMEDIR}"
    log 'home directory %s created' "${HOMEDIR}"
  fi
  chown "${USER}:${USER}" "${HOMEDIR}"
  [ -d "${HOMEDIR}/.ssh" ] || ln -s "./" "${HOMEDIR}/.ssh"
  if [ -f "${HOMEDIR}/.ssh/id_ed25519" ]; then
    warn 'ssh key %s already exists' "${HOMEDIR}/.ssh/id_ed25519"
  else
    su -c "ssh-keygen -f '${HOMEDIR}/.ssh/id_ed25519' -t ed25519 -N ''" - "${USER}"
    log 'ssh key %s created' "${HOMEDIR}/.ssh/id_ed25519"
  fi
  # shellcheck disable=2016 # ignore warning about not expanding
  printf 'run the following command on the remote backup server (replace <dataset_root> with the actual dataset root):\n'
  printf 'zfsync allowreceive <dataset_root> "%s"\n' "$(cat "${HOMEDIR}/.ssh/id_ed25519.pub")"
}

restart_as_root() {
  if [ "$(id -u)" -ne 0 ]; then
    warn "restarting as root ..."
    exec sudo -E "$0" "$@"
  fi
}

allowsend() {
  DATASET="$1"
  USER="${2:-"zfsync"}"
  PERMS="send,snapshot,bookmark,hold"
  log "granting '%s' permissions to '%s' on dataset '%s'" "${PERMS}" "${USER}" "${DATASET}"
  zfs allow "${USER}" "${PERMS}" "${DATASET}"
  zfs allow "${DATASET}"
  # shellcheck disable=2016 # don't expand command below
  HOMEDIR="$(su -c 'echo "$HOME"' - "${USER}")"
  if [ -f "${HOMEDIR}/.ssh/id_ed25519.pub" ]; then
    # shellcheck disable=2016 # don't execute command below
    warn 'use the following key with the `zfs allowreceive` command on the remote backup server:'
    cat "${HOMEDIR}/.ssh/id_ed25519.pub"
  else
    warn 'public key not found at: %s' "${HOMEDIR}/.ssh/id_ed25519"
  fi
}

allowreceive() {
  DATASET="$1"
  KEY="$2"
  USER="${3:-"zfsync"}"
  PERMS='receive,mount,create,userprop,encryption,canmount,mountpoint,compression,destroy,send,bookmark,keylocation'
  if ! zfs list "${DATASET}" >/dev/null 2>&1; then
    warn 'creating dataset %s' "${DATASET}"
    zfs create -o mountpoint=none -p "${DATASET}"
  fi
  log "granting '%s' permission to '%s' on dataset '%s'" "${PERMS}" "${USER}" "${DATASET}"
  zfs allow "${USER}" "${PERMS}" "${DATASET}"
  zfs allow "${DATASET}"
  AUTHCMD="restrict,command=\"zfsync server ${DATASET}\" ${KEY}"
  # shellcheck disable=2016 # don't expand $HOME below
  HOMEDIR="$(su -c 'echo "$HOME"' - "${USER}")"
  if grep -q "${AUTHCMD}" "${HOMEDIR}/.ssh/authorized_keys" 2>/dev/null; then
    log 'authorized_keys file already contains the specified key'
  elif grep "${KEY}" "${HOMEDIR}/.ssh/authorized_keys" 2>/dev/null; then
    warn '%s already contains the specified key; but may not be correct' "${HOMEDIR}/.ssh/authorized_keys"
    warn 'manually update with the following:'
    echo "${AUTHCMD}"
  else
    log 'updating %s' "${HOMEDIR}/.ssh/authorized_keys"
    echo "${AUTHCMD}" >> "${HOMEDIR}/.ssh/authorized_keys"
  fi
}

if [ "${1:-}" = '-d' ]; then
  DEBUG=true
  shift
fi
CMD="${1:-}"
[ $# -gt 0 ] && shift
case "${CMD}" in
  'snap')
    # help: \nsnap: create new snapshot(s)
    # help:   zfsync snap [-r|-d depth] <dataset> ...
    snap "$@";;
  'mirror')
    # help: \nmirror: mirror snapshot(s) to remote server
    # help:   zfsync mirror <host> [-r|-d depth] <dataset> ...
    HOST="$1"; shift
    connect "${HOST}"
    mirror "$@";;
  'backup')
    # help: \nbackup: run `snap` and then `mirror` in a single command
    # help:   zfsync backup <host> [-r|-d depth] <dataset> ...
    HOST="$1"; shift
    snap "$@"
    connect "${HOST}"
    mirror "$@";;
  'server')
    # help: \nserver: run in server mode on the backup host (from .ssh/authorized_keys file)
    # help:   zfsync server <dataset_root>
    server "$@";;
  'list')
    # help: \nlist: run `zfs list` remotely on backup server (ie. query the backup server from the client)
    # help:   zfsync list <host> [options] <dataset> ...
    HOST="$1"; shift
    connect "${HOST}"
    $RPC list "$@";;
  'destroy')
    # help: \ndestroy: run `zfs destroy` remotely on backup server (ie. destroy dataset on server from the client)
    # help:   zfsync destroy <host> [options] <dataset>
    HOST="$1"; shift
    connect "${HOST}"
    $RPC destroy "$@";;
  'recover')
    # help: \nrecover: run `zfs send` remotely on backup server (ie. to restore a snaphshot from the backup server)
    # help:   zfsync recover <host> [options] <dataset>
    HOST="$1"; shift
    connect "${HOST}"
    $RPC send "$@";;
  'configuser')
    # help: \nconfiguser: create zfsync user, /etc/zfsync directory, and /etc/zfsync/id_ed25519 ssh key
    # help:   zfsync configuser [username] [home_dir]
    restart_as_root configuser "$@"
    configuser "$@";;
  'allowsend')
    # help: \nallowsend: delegate zfs permissions to zfsync user to be able to send dataset (on client)
    # help:   zfsync allowsend <dataset> [username]
    restart_as_root allowsend "$@"
    allowsend "$@";;
  'allowreceive')
    # help: \nallowreceive: delegate zfs permissions to zfsync user to be able to receive into dataset (on server)
    # help:   zfsync allowreceive <dataset> <key> [username]
    restart_as_root allowreceive "$@"
    allowreceive "$@";;
  *)
    case "${CMD}" in
      '-h'|'--help')
        ;;
      *)
        error "\nfatal error: unknown command%s" "${CMD:+": \`${CMD}\`"}"
        ;;
    esac
    printf 'zfsync is a shell script to create and mirror zfs snapshots.\nusage:\n'
    grep '# help: ' "$0" | grep -v 'grep' | sed 's/ *# help: //g' | sed 's/\\n/\n/g';;
esac
